apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apichart.fullname" . }}
  labels:
    app: {{ .Values.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name  }}
          image: "{{ .Values.version | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            request:
              cpu: {{ .Values.cpu  }}
              memory: {{ .Values.memory  }}
