apiVersion: v1
kind: Service
metadata:
  name: {{ include "apichart.fullname" . }}
  labels:
    {{- include "apichart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.app }}
    {{- include "apichart.selectorLabels" . | nindent 4 }}
